In [1]:
import tensorflow as tf

tf.__version__

'1.15.0'

In [2]:
# 상수정의
a = tf.constant(1234)
b = tf.constant(5000)

# 계산정의
add_op = a+b

#세션 시작
sess = tf.Session()
res = sess.run(add_op)
res

6234

In [3]:
#상수 정의
a = tf.constant(2) 
b = tf.constant(3)
c = tf.constant(4)

#계산 정의
calc1_op = a + b *c
calc2_op = (a+b) * c

#세션 시작 
sess = tf.Session() 
res1 = sess.run(calc1_op) #계산식 평가 
print(res1)
res2 = sess.run(calc2_op) #계산식 평가 
print(res2)

14
20


In [7]:
#상수 정의
a = tf.constant(100) 
b = tf.constant(50)
add_op = a + b

#변수 v 선언하기, 초기값:0
v = tf.Variable(0)

# 변수 v에 add_op의 결과 대입하기
let_op = tf.assign(v, add_op)

#세션 시작 
sess = tf.Session() 
# 변수 초기화히기
sess.run(tf.global_variables_initializer())
#계산식 실행
sess.run(let_op) 
print(sess.run(v))

10


In [8]:
#placeholder 정의(정수 자료형 3개를 가진 배열)
a = tf.placeholder(tf.int32, [3]) 
b = tf.constant(2)
x2_op = a * b

#세션 시작 
sess = tf.Session() 
# placeholder에 값 넣고 실행하기
r1 = sess.run(x2_op, feed_dict = {a:[1, 2, 3]})
print(r1)
r2 = sess.run(x2_op, feed_dict = {a:[10, 20, 10]})
print(r2)

[2 4 6]
[20 40 20]


In [9]:
#placeholder 정의( 배열의 크기를 None으로 지정)
a = tf.placeholder(tf.int32, [None]) 
b = tf.constant(10)
x10_op = a* b

#세션 시작 
sess = tf.Session() 
# placeholder에 값 넣고 실행하기
r1 = sess.run(x10_op, feed_dict = {a:[1, 2, 3, 4, 5]})
print(r1)
r2 = sess.run(x10_op, feed_dict = {a:[10, 20]})
print(r2)

[10 20 30 40 50]
[100 200]


In [35]:
# output path 받기
from pathlib import Path
cur_path = Path(Path.cwd())
root_path = cur_path.parent.parent.parent
goal_path = root_path / 'datas/실습/output/12월/30일/'
goal_path

WindowsPath('C:/Users/student/Desktop/깃/TIL/datas/실습/output/12월/30일')

In [21]:
a = tf.constant(100, name="a")
b = tf.constant(200, name="b")
c = tf.constant(300, name="c")
v = tf.Variable(0, name="v")
# 곱셈을 수행하는 그래프 정의하기  
calc_op = a + b * c 
assign_op = tf.assign(v, calc_op)
# 세션 생성하기  
sess = tf.Session()
# TensorBoard 사용하기  
tw = tf.summary.FileWriter(goal_path+"log_dir", graph=sess.graph)
# 세션 실행하기   
sess.run(assign_op)
print(sess.run(v))

60100


In [30]:
import numpy as np

def get_top(x, mx, y, my):
    d = 0
    for i in range(len(x)):
        d += (x[i]-mx) * (y[i]-my)
    return d

x = [2, 4, 6, 8]
y = [81, 93, 91, 97]

mx = np.mean(x)
my = np.mean(y)
print('x의 평균값 ', mx)
print('y의 평균값 ', my)

divisor = sum([(mx -i)**2 for i in x])
top = get_top(x, mx, y, my)
a = top/divisor
b = my - (mx*a)

print('분자 ', top)
print('분모 ', divisor)
print('기울기 ', a)
print('y절편 ', b)

x의 평균값  5.0
y의 평균값  90.5
분자  46.0
분모  20.0
기울기  2.3
y절편  79.0


In [36]:
#  임의의 기울기와 절편
ab = [3, 76]

data = [[2,81],[4,93],[6,91],[8,97]]

# x 값과 y 값
x= [ i[0] for i in data]
y= [ i[1] for i in data]


#  임의의 기울기와 절편의 모델로부터 예측값 반환 함수
def predict(x):
    return ab[0]*x+ab[1]

# 평균 제곱근 오차 반환 함수
def rmse(p, a):
    return    np.sqrt(((p-a)**2).mean())

predict_result = []

for i in range(len(x)):
    predict_result.append(predict(x[i]))
    print("공부한 시간 =%.f, 실제 점수 =%.f,  예측점수=%.f" % (x[i], y[i], predict_result[i]))

# 평균 제곱근 오차 반환 함수를 이용해서 최종값 구하기
def  rmse_val(predict_result, y) :
    return rmse(np.array(predict_result), np.array(y))

print("rmse  최종값 :"+ str(rmse_val(predict_result, y)))

공부한 시간 =2, 실제 점수 =81,  예측점수=82
공부한 시간 =4, 실제 점수 =93,  예측점수=88
공부한 시간 =6, 실제 점수 =91,  예측점수=94
공부한 시간 =8, 실제 점수 =97,  예측점수=100
rmse  최종값 :3.3166247903554


In [37]:
data = [[2,81],[4,93],[6,91],[8,97]]

# x 값과 y 값
x_data= [ i[0] for i in data]
y_data= [ i[1] for i in data]

#임의의 기울기와 y절편의 값으로 변수로 정의
a=tf.Variable(tf.random_uniform([1], 0, 10, dtype=tf.float64, seed=0))   #기울기 범위 0~10
b = tf.Variable(tf.random_uniform([1], 0, 100, dtype=tf.float64, seed=0))   #y절편 범위 0~100

y = a*x_data+b  #1차방정식의 계산식 정의

#오차 계산 (평균 제곱근 오차 공식)
rmse = tf.sqrt(tf.reduce_mean(tf.square(y-y_data)))

#학습률
learning_rate = 0.1

# 오차 rmse 값이 최소인 값 찾는 식 정의
gradient_descent = tf.train.GradientDescentOptimizer(learning_rate).minimize(rmse)

#텐서플로으로 학습
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())     # 변수들을 메모리에 생성, 초기화
    for step in range(2001):
        sess.run(gradient_descent)
        if step % 100 == 0:
            print("Epoch: %.f , RMSE=%.4f,  기울기 a=%.4f, 절편 b= %.4f" % (step, sess.run(rmse), sess.run(a), sess.run(b)))

#Epoch는 입력값에 대해 몇 번 반복 실험했는지를 나타내는 용어

Epoch: 0 , RMSE=30.2139,  기울기 a=7.5235, 절편 b= 80.5984
Epoch: 100 , RMSE=2.8860,  기울기 a=2.2299, 절편 b= 79.4181
Epoch: 200 , RMSE=2.8826,  기울기 a=2.2601, 절편 b= 79.2379
Epoch: 300 , RMSE=2.8815,  기울기 a=2.2773, 절편 b= 79.1353
Epoch: 400 , RMSE=2.8811,  기울기 a=2.2871, 절편 b= 79.0770
Epoch: 500 , RMSE=2.8810,  기울기 a=2.2927, 절편 b= 79.0438
Epoch: 600 , RMSE=2.8810,  기울기 a=2.2958, 절편 b= 79.0249
Epoch: 700 , RMSE=2.8810,  기울기 a=2.2976, 절편 b= 79.0142
Epoch: 800 , RMSE=2.8810,  기울기 a=2.2987, 절편 b= 79.0081
Epoch: 900 , RMSE=2.8810,  기울기 a=2.2992, 절편 b= 79.0046
Epoch: 1000 , RMSE=2.8810,  기울기 a=2.2996, 절편 b= 79.0026
Epoch: 1100 , RMSE=2.8810,  기울기 a=2.2998, 절편 b= 79.0015
Epoch: 1200 , RMSE=2.8810,  기울기 a=2.2999, 절편 b= 79.0008
Epoch: 1300 , RMSE=2.8810,  기울기 a=2.2999, 절편 b= 79.0005
Epoch: 1400 , RMSE=2.8810,  기울기 a=2.3000, 절편 b= 79.0003
Epoch: 1500 , RMSE=2.8810,  기울기 a=2.3000, 절편 b= 79.0002
Epoch: 1600 , RMSE=2.8810,  기울기 a=2.3000, 절편 b= 79.0001
Epoch: 1700 , RMSE=2.8810,  기울기 a=2.3000, 절편 b= 79.0001
Epo

In [46]:
data = [[2,0,81],[4,4,93],[6,2,91],[8,3,97]]
x1_data= [i[0] for i in data]
x2_data= [i[1] for i in data]
y_data= [i[2] for i in data]

a = tf.Variable(tf.random_uniform([2], 0, 10, dtype=tf.float64, seed=0))   
b = tf.Variable(tf.random_uniform([1], 0, 100, dtype=tf.float64, seed=0))

y = a[0]*x1_data + a[1]*x2_data + b
rmse = tf.sqrt(tf.reduce_mean(tf.square(y-y_data)))
learning_rate = 0.01
gradient_descent = tf.train.GradientDescentOptimizer(learning_rate).minimize(rmse)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())     # 변수들을 메모리에 생성, 초기화
    for step in range(4001):
        sess.run(gradient_descent)
        if step % 100 == 0:
            print("Epoch: %s, RMSE=%s,  기울기 a=%s, 절편 b=%s" % (step, sess.run(rmse), sess.run(a), sess.run(b)))

Epoch: 0, RMSE=52.05538913854395,  기울기 a=[8.01479204 7.8758647 ], 절편 b=[80.68091405]
Epoch: 100, RMSE=15.649840464630143,  기울기 a=[2.62804395 5.31848417], 절편 b=[79.75946617]
Epoch: 200, RMSE=1.818026362141177,  기울기 a=[0.68531997 3.54303178], 절편 b=[79.3071515]
Epoch: 300, RMSE=0.8021130261500584,  기울기 a=[1.11784738 2.65186766], 절편 b=[79.13956499]
Epoch: 400, RMSE=0.4799166862030859,  기울기 a=[1.33871183 2.27732645], 절편 b=[78.83715985]
Epoch: 500, RMSE=0.38144108322033826,  기울기 a=[1.40090437 2.253383  ], 절편 b=[78.53245878]
Epoch: 600, RMSE=0.3177708886385602,  기울기 a=[1.43785766 2.26429304], 절편 b=[78.28371738]
Epoch: 700, RMSE=0.2857294010949991,  기울기 a=[1.46347526 2.27310347], 절편 b=[78.10792064]
Epoch: 800, RMSE=0.2732880784679609,  기울기 a=[1.47937105 2.27859158], 절편 b=[77.99878117]
Epoch: 900, RMSE=0.2691372251001448,  기울기 a=[1.48853503 2.28175569], 절편 b=[77.93586132]
Epoch: 1000, RMSE=0.2678358339001462,  기울기 a=[1.4936626  2.28352613], 절편 b=[77.9006554]
Epoch: 1100, RMSE=0.2674363380459786

In [59]:
import tensorflow as tf 
import numpy as np

data =[[2, 0], [4, 0], [6, 0], [8, 1], [10, 1], [12, 1], [14, 1]]

x_data = [i[0] for i in data]
y_data = [i[1] for i in data]

#임의의 a, b 값을 변수로 정의
a = tf.Variable(tf.random_normal([1], dtype=tf.float64, seed=0))
b = tf.Variable(tf.random_normal([1], dtype=tf.float64, seed=0))

#시그모이드 함수 방정식 정의
y = 1/ (1+ np.e**(a*x_data+b))

#오차 loss 구하는 함수
loss = -tf.reduce_mean(np.array(y_data)*tf.log(y)+(1-np.array(y_data))*tf.log(1-y))

#학습률 
learning_rate = 0.5

# 오차 rmse 값이 최소인 값 찾는 식 정의
gradient_descent = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)

#텐서플로 이용하여 학습
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())     # 변수들을 메모리에 생성, 초기화
    for step in range(10000):
        sess.run(gradient_descent)
        if step % 1000 == 0:
            print("Epoch: %.f , loss=%.4f,  기울기 a=%.4f, 절편 b= %.4f" % (step, sess.run(loss), sess.run(a), sess.run(b)))

Epoch: 0 , loss=1.2676,  기울기 a=0.1849, 절편 b= -0.4334
Epoch: 1000 , loss=0.0557,  기울기 a=-1.6009, 절편 b= 11.0214
Epoch: 2000 , loss=0.0361,  기울기 a=-2.0366, 절편 b= 14.0912
Epoch: 3000 , loss=0.0269,  기울기 a=-2.3381, 절편 b= 16.2089
Epoch: 4000 , loss=0.0214,  기울기 a=-2.5708, 절편 b= 17.8419
Epoch: 5000 , loss=0.0178,  기울기 a=-2.7607, 절편 b= 19.1736
Epoch: 6000 , loss=0.0152,  기울기 a=-2.9211, 절편 b= 20.2983
Epoch: 7000 , loss=0.0133,  기울기 a=-3.0600, 절편 b= 21.2716
Epoch: 8000 , loss=0.0118,  기울기 a=-3.1824, 절편 b= 22.1293
Epoch: 9000 , loss=0.0106,  기울기 a=-3.2918, 절편 b= 22.8958


In [62]:
import tensorflow as tf 
import numpy as np

x_data = np.array( [[2,3],[4,3],[6,4],[8,6],[10, 7], [12, 8], [14, 9]] )
y_data= np.array([0, 0, 0, 1, 1, 1,1] ).reshape(7, 1)

#입력값을 placeholder에 저장
X= tf.placeholder(tf.float64, shape=[None, 2])
Y = tf.placeholder(tf.float64, shape=[None, 1])
 
#실행할 때마다 동일한 출력(결과)를 얻기 위한 값 설정
seed = 0
np.random.seed(seed)
tf.set_random_seed(seed)

#임의의 a, b 값을 변수로 정의
a = tf.Variable(tf.random_uniform([2, 1], dtype=tf.float64))  #[2, 1]은 들어오는  값은 2개 나가는 값은 1개
b = tf.Variable(tf.random_uniform([1], dtype=tf.float64))

#시그모이드 함수 방정식 정의
y = tf.sigmoid(tf.matmul(X, a) + b)

#오차 loss 구하는 함수
loss = -tf.reduce_mean(Y*tf.log(y)+(1-Y)*tf.log(1-y))

#학습률
learning_rate = 0.1

# 오차 loss 값이 최소인 값 찾는 식 정의
gradient_descent = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)

predicted = tf.cast(y >0.5, dtype=tf.float64)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float64))

#tf.cast() 함수는 형변환(캐스팅) 수행 => 부동소수점형(실수)를 정수형으로 변환할때는 소수점이하 버림
#bool (논리) 자료형을 정수형으로 변환할때는 True는 1, False는 0으로

#텐서플로 이용하여 학습
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())     # 변수들을 메모리에 생성, 초기화
    for step in range(10000):
        a_, b_, loss_, _ = sess.run([a, b, loss, gradient_descent], feed_dict={X:x_data, Y:y_data})
        if step % 500 == 0:
            print("Epoch: %.f , loss=%.4f,  기울기 a1=%.4f, 기울기 a2=%.4f, 절편 b= %.4f" % (step,  loss_,  a_[0], a_[1],  b_))

Epoch: 0 , loss=1.7127,  기울기 a1=0.7648, 기울기 a2=-0.1155, 절편 b= 0.1099
Epoch: 500 , loss=0.2116,  기울기 a1=0.8842, 기울기 a2=-0.4585, 절편 b= -3.4744
Epoch: 1000 , loss=0.1402,  기울기 a1=0.7203, 기울기 a2=0.1077, 절편 b= -5.2530
Epoch: 1500 , loss=0.1040,  기울기 a1=0.5442, 기울기 a2=0.5924, 절편 b= -6.4903
Epoch: 2000 , loss=0.0823,  기울기 a1=0.3967, 기울기 a2=0.9838, 절편 b= -7.4422
Epoch: 2500 , loss=0.0679,  기울기 a1=0.2770, 기울기 a2=1.3023, 절편 b= -8.2164
Epoch: 3000 , loss=0.0578,  기울기 a1=0.1794, 기울기 a2=1.5665, 절편 b= -8.8691
Epoch: 3500 , loss=0.0503,  기울기 a1=0.0987, 기울기 a2=1.7901, 절편 b= -9.4335
Epoch: 4000 , loss=0.0445,  기울기 a1=0.0309, 기울기 a2=1.9828, 절편 b= -9.9307
Epoch: 4500 , loss=0.0399,  기울기 a1=-0.0272, 기울기 a2=2.1515, 절편 b= -10.3750
Epoch: 5000 , loss=0.0362,  기울기 a1=-0.0777, 기울기 a2=2.3013, 절편 b= -10.7766
Epoch: 5500 , loss=0.0331,  기울기 a1=-0.1221, 기울기 a2=2.4357, 절편 b= -11.1430
Epoch: 6000 , loss=0.0305,  기울기 a1=-0.1616, 기울기 a2=2.5575, 절편 b= -11.4799
Epoch: 6500 , loss=0.0283,  기울기 a1=-0.1972, 기울기 a2=2.6689, 

In [63]:
import tensorflow as tf 
import numpy as np

#가중치와 바이어스
w11 = np.array([-2, -2])
w12 = np.array([2, 2])

w2 = np.array([1, 1])

b1 = 3
b2 = -1
b3 = -1

#퍼셉트론
def MLP(x, w, b):
    y = np.sum(w*x) + b
    if y<=0:
        return 0
    else :
        return 1


#NAND게이트
def NAND(x1, x2):
    return MLP(np.array([x1, x2]), w11, b1)

#OR게이트
def OR(x1, x2):
    return MLP(np.array([x1, x2]), w12, b2)

#AND게이트
def AND(x1, x2):
    return MLP(np.array([x1, x2]), w2, b3)

#XOR게이트
def XOR(x1, x2):
    return  AND(NAND(x1,x2), OR(x1, x2))

if __name__ =='__main__' :
    for x in [(0, 0), (0, 1), (1, 0), (1, 1)] :
        y = XOR(x[0], x[1])
        print("입력값 :"+str(x) +"   출력값 :"+ str(y))


입력값 :(0, 0)   출력값 :0
입력값 :(0, 1)   출력값 :1
입력값 :(1, 0)   출력값 :1
입력값 :(1, 1)   출력값 :0
